enum VoiceError {
  NO_PERMISSION = 'NO_PERMISSION',
  NOT_SUPPORTED = 'NOT_SUPPORTED',
  SOCKET_ERROR = 'SOCKET_ERROR',
  RESPONSE_ERROR = 'RESPONSE_ERROR',
  WORKLET_ERROR = 'WORKLET_ERROR',
  GENERAL_ERROR = 'GENERAL_ERROR',
}

export default VoiceError;
