extends: 
  - airbnb
  - airbnb/hooks
  - "plugin:import/typescript"
  - prettier
  - prettier/react
parser: babel-eslint
plugins: 
  - prettier
rules: 
  react/jsx-filename-extension: 0 # allow jsx in non .jsx files
  react/jsx-props-no-spreading: 0 # allow spreading props
  import/extensions: 
    - 2
    - ignorePackages
    - 
      ts: never
      tsx: never
overrides:
  -
    extends:
      - "plugin:@typescript-eslint/recommended"
      - "prettier/@typescript-eslint"
    files: ["*.ts", "*.tsx"]
    rules:
      "@typescript-eslint/no-unused-vars": 2

      # these are checked by the TS compiler
      react/forbid-prop-types: 0
      react/jsx-no-undef: 0
      react/no-unused-prop-types: 0
      react/prop-types: 0
      react/react-in-jsx-scope: 0

      # allow ts-ignore comments
      "@typescript-eslint/ban-ts-comment": 0

      # ensure variables, functions, and properties are camelCase, UPPER_CASE, or PascalCase
      # ensure types are PascalCase
      "@typescript-eslint/naming-convention":
        - 2
        - selector: variableLike
          format:
            - camelCase
            - UPPER_CASE
            - PascalCase
        - selector: memberLike
          # allow double underscore prefix (e.g. __html)
          filter:
            regex: ^__
            match: false
          format:
            - camelCase
            - UPPER_CASE
            - PascalCase
        - selector: typeLike
          format:
            - PascalCase
