import Word from 'types/Word';

// a hard coded sample verse
// currently we use it in QuranFontSection, so we can show the preview of the verse
// when use users are changing the font size, style, etc
const verseSample = {
  id: 16,
  verseNumber: 9,
  verseKey: '2:9',
  juzNumber: 1,
  hizbNumber: 1,
  rubNumber: 1,
  sajdahType: null,
  sajdahNumber: null,
  textUthmani:
    'يُخَـٰدِعُونَ ٱللَّهَ وَٱلَّذِينَ ءَامَنُوا۟ وَمَا يَخْدَعُونَ إِلَّآ أَنفُسَهُمْ وَمَا يَشْعُرُونَ',
  chapterId: 2,
  pageNumber: 3,
  words: [
    {
      id: 9694,
      position: 1,
      audioUrl: 'wbw/002_009_001.mp3',
      charTypeName: 'word',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:1',
      qpcUthmaniHafs: 'يُخَٰدِعُونَ',
      pageNumber: 3,
      lineNumber: 5,
      text: 'يُخَٰدِعُونَ',
      translation: {
        text: 'They seek to deceive',
        languageName: 'english',
      },
      transliteration: {
        text: 'yukhādiʿūna',
        languageName: 'english',
      },
    },
    {
      id: 9695,
      position: 2,
      audioUrl: 'wbw/002_009_002.mp3',
      charTypeName: 'word',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:2',
      qpcUthmaniHafs: 'ٱللَّهَ',
      pageNumber: 3,
      lineNumber: 5,
      text: 'ٱللَّهَ',
      translation: {
        text: 'Allah',
        languageName: 'english',
      },
      transliteration: {
        text: 'l-laha',
        languageName: 'english',
      },
    },
    {
      id: 9696,
      position: 3,
      audioUrl: 'wbw/002_009_003.mp3',
      charTypeName: 'word',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:3',
      qpcUthmaniHafs: 'وَٱلَّذِينَ',
      pageNumber: 3,
      lineNumber: 5,
      text: 'وَٱلَّذِينَ',
      translation: {
        text: 'and those who',
        languageName: 'english',
      },
      transliteration: {
        text: 'wa-alladhīna',
        languageName: 'english',
      },
    },
    {
      id: 9697,
      position: 4,
      audioUrl: 'wbw/002_009_004.mp3',
      charTypeName: 'word',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:4',
      qpcUthmaniHafs: 'ءَامَنُواْ',
      pageNumber: 3,
      lineNumber: 5,
      text: 'ءَامَنُواْ',
      translation: {
        text: 'believe[d]',
        languageName: 'english',
      },
      transliteration: {
        text: 'āmanū',
        languageName: 'english',
      },
    },
    {
      id: 9698,
      position: 5,
      audioUrl: 'wbw/002_009_005.mp3',
      charTypeName: 'word',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:5',
      qpcUthmaniHafs: 'وَمَا',
      pageNumber: 3,
      lineNumber: 5,
      text: 'وَمَا',
      translation: {
        text: 'and not',
        languageName: 'english',
      },
      transliteration: {
        text: 'wamā',
        languageName: 'english',
      },
    },
    {
      id: 9699,
      position: 6,
      audioUrl: 'wbw/002_009_006.mp3',
      charTypeName: 'word',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:6',
      qpcUthmaniHafs: 'يَخۡدَعُونَ',
      pageNumber: 3,
      lineNumber: 5,
      text: 'يَخۡدَعُونَ',
      translation: {
        text: 'they deceive',
        languageName: 'english',
      },
      transliteration: {
        text: 'yakhdaʿūna',
        languageName: 'english',
      },
    },
    {
      id: 9700,
      position: 7,
      audioUrl: 'wbw/002_009_007.mp3',
      charTypeName: 'word',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:7',
      qpcUthmaniHafs: 'إِلَّآ',
      pageNumber: 3,
      lineNumber: 5,
      text: 'إِلَّآ',
      translation: {
        text: 'except',
        languageName: 'english',
      },
      transliteration: {
        text: 'illā',
        languageName: 'english',
      },
    },
    {
      id: 9701,
      position: 8,
      audioUrl: 'wbw/002_009_008.mp3',
      charTypeName: 'word',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:8',
      qpcUthmaniHafs: 'أَنفُسَهُمۡ',
      pageNumber: 3,
      lineNumber: 5,
      text: 'أَنفُسَهُمۡ',
      translation: {
        text: 'themselves',
        languageName: 'english',
      },
      transliteration: {
        text: 'anfusahum',
        languageName: 'english',
      },
    },
    {
      id: 9702,
      position: 9,
      audioUrl: 'wbw/002_009_009.mp3',
      charTypeName: 'word',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:9',
      qpcUthmaniHafs: 'وَمَا',
      pageNumber: 3,
      lineNumber: 6,
      text: 'وَمَا',
      translation: {
        text: 'and not',
        languageName: 'english',
      },
      transliteration: {
        text: 'wamā',
        languageName: 'english',
      },
    },
    {
      id: 9703,
      position: 10,
      audioUrl: 'wbw/002_009_010.mp3',
      charTypeName: 'word',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:10',
      qpcUthmaniHafs: 'يَشۡعُرُونَ',
      pageNumber: 3,
      lineNumber: 6,
      text: 'يَشۡعُرُونَ',
      translation: {
        text: 'they realize (it)',
        languageName: 'english',
      },
      transliteration: {
        text: 'yashʿurūna',
        languageName: 'english',
      },
    },
    {
      id: 9704,
      position: 11,
      audioUrl: null,
      charTypeName: 'end',
      verseKey: '2:9',
      verseId: 16,
      location: '2:9:11',
      qpcUthmaniHafs: '٩',
      pageNumber: 3,
      lineNumber: 6,
      text: '٩',
      translation: {
        text: 'Ayah 9',
        languageName: 'english',
      },
      transliteration: {
        text: null,
        languageName: 'english',
      },
    },
  ] as Word[],
  timestamps: {
    timestampFrom: 131336,
    timestampTo: 158776,
    duration: 32000,
    segments: [
      [0, 131336, 133006],
      [1, 133016, 133966],
      [2, 133976, 135436],
      [3, 135446, 136936],
      [4, 136946, 137676],
      [5, 137686, 139276],
      [6, 139286, 141586],
      [7, 141596, 143836],
      [8, 148436, 156176],
      [9, 156186, 158176],
    ],
  },
  translations: [
    {
      id: 903973,
      resourceId: 131,
      text: 'They seek to deceive Allah and the believers, yet they only deceive themselves, but they fail to perceive it.',
      resourceName: 'Dr. Mustafa Khattab, the Clear Quran',
    },
    {
      id: 98521,
      resourceId: 20,
      text: 'They [think to] deceive Allah and those who believe, but they deceive not except themselves and perceive [it] not.',
      resourceName: 'Saheeh International',
    },
  ],
};

export default verseSample;
