enum QueryParam {
  Translations = 'translations',
  Reciter = 'reciter',
  WBW_LOCALE = 'wbw_locale',
  HIDE_ARABIC = 'hideArabic',
  FLOW = 'flow',
  STARTING_VERSE = 'startingVerse',
  QUERY = 'query',
  REDIRECT_TO = 'r',
  VERSE_TO = 'verseTo',
  VERSE_FROM = 'verseFrom',
  SHOULD_HAVE_BORDER = 'shouldHaveBorder',
  BACKGROUND_COLOR_ID = 'backgroundColorId',
  OPACITY = 'opacity',
  MEDIA_RECITER = 'mediaReciter',
  QURAN_TEXT_FONT_SCALE = 'quranTextFontScale',
  QURAN_TEXT_FONT_STYLE = 'quranTextFontStyle',
  TRANSLATION_FONT_SCALE = 'translationFontScale',
  MEDIA_TRANSLATIONS = 'mediaTranslations',
  FONT_COLOR = 'fontColor',
  VERSE_ALIGNMENT = 'verseAlignment',
  TRANSLATION_ALIGNMENT = 'translationAlignment',
  ORIENTATION = 'orientation',
  VIDEO_ID = 'videoId',
  SURAH = 'surah',
}

export default QueryParam;
