import { TranslateFn } from './types';

import type { ActiveFilterChip } from '@/components/MyQuran/SavedTabContent/ActiveFiltersChips';
import type { CollectionFiltersDropdownProps } from '@/components/MyQuran/SavedTabContent/CollectionFiltersDropdown';
import Bookmark from '@/types/Bookmark';
import { CollectionDetailSortOption } from 'types/CollectionSortOptions';

export interface CollectionDetailViewLayoutProps {
  collectionName: string;
  onBack: () => void;
  isDefault?: boolean;
  lang: string;
  t: TranslateFn;
  numericCollectionId: string;
  sortBy: CollectionDetailSortOption;
  onSortByChange: (newSortBy: CollectionDetailSortOption) => void;
  totalCount: number;
  isOwner: boolean;
  emptyMessage: string;
  filteredBookmarks: Bookmark[];
  onItemDeleted: (bookmarkId: string) => void;
  onShareVerse: (verseKey: string) => void;
  isSelectMode: boolean;
  isAllExpanded: boolean;
  selectedCount: number;
  onToggleSelectMode: () => void;
  onToggleExpandCollapseAll: () => void;
  onToggleBookmarkSelection: (bookmarkId: string) => void;
  onToggleCardExpansion: (bookmarkId: string) => void;
  isCardExpanded: (bookmarkId: string) => boolean;
  isBookmarkSelected: (bookmarkId: string) => boolean;
  onHeaderNoteClick: () => void;
  onHeaderPinAllClick: () => void;
  onHeaderEditClick: () => void;
  onHeaderDeleteClick: () => void;
  onBulkNoteClick: () => void;
  onBulkPinSelectedClick: () => void;
  onBulkCopyClick: () => void;
  onBulkDeleteClick: () => void;
  shareVerseKey: string | null;
  onShareModalClose: () => void;
  isDeleteBookmarksModalOpen: boolean;
  isDeletingBookmarks: boolean;
  pendingDeleteBookmarkIds: string[];
  onBulkDeleteCancel: () => void;
  onBulkDeleteConfirm: () => void;
  isNoteModalOpen: boolean;
  noteModalVerseKeys: string[];
  onNoteModalClose: () => void;
  isEditModalOpen: boolean;
  onEditSubmit: (formData: { name: string }) => Promise<void>;
  onEditModalClose: () => void;
  isDeleteCollectionModalOpen: boolean;
  onDeleteCollectionConfirm: () => void;
  onDeleteCollectionCancel: () => void;
  isDeletingCollection: boolean;

  chapterItems: CollectionFiltersDropdownProps['chapterItems'];
  juzItems: CollectionFiltersDropdownProps['juzItems'];
  selectedChapterIds: string[];
  selectedJuzNumbers: string[];
  onSelectedChapterIdsChange: (chapterIds: string[]) => void;
  onSelectedJuzNumbersChange: (juzNumbers: string[]) => void;
  activeChapterChips: ActiveFilterChip[];
  activeJuzChips: ActiveFilterChip[];
  hasActiveFilters: boolean;
  onRemoveChapterFilter: (chapterId: string) => void;
  onRemoveJuzFilter: (juzNumber: string) => void;
  onClearAllFilters: () => void;
}
