blank_issues_enabled: true
contact_links:
  - name: Quranic tech Community
    url: https://quran-community.herokuapp.com/
    about: We are trying to bring together the open-source community working around Quranic tech and Islamic applications. Join us!