import PostComment from './PostComment';
import QuranreflectUser from './QuranreflectUser';
import Reference from './Reference';
import Room from './Room';
import Tag from './Tag';

interface AyahReflection {
  id: number;
  authorId: string;
  body?: string;
  discussionId?: number;
  draft?: boolean;
  createdAt: string;
  updatedAt: Date;
  publishedAt?: Date;
  global?: boolean;
  toxicityScore?: number;
  reported?: boolean;
  views?: number;
  customLastUpdated?: Date;
  removed?: boolean;
  reportedAt?: Date;
  removedAt?: Date;
  restoredAt?: Date;
  verified?: boolean;
  roomPostStatus?: number;
  hidden?: boolean;
  commentsCount: number;
  likesCount?: number;
  viewsCount?: number;
  languageId?: number;
  languageName?: string;
  moderationStatus?: number;
  shareToken?: string;
  default?: boolean;
  reviewStatus?: number;
  postedById?: string;
  reviewedAt?: Date;
  reviewedById?: number;
  timeToReview?: number;
  featuredAt?: Date;
  estimatedReadingTime?: number;
  reviewAssigneeId?: number;
  reviewAssigneeReviewedAt?: Date;
  roomId: number;
  postTypeId: number;
  postTypeName?: string;
  isLiked?: boolean;
  isSaved?: boolean;
  isCommentedOn?: boolean;
  isByFollowedUser?: boolean;
  author?: QuranreflectUser;
  room?: Room;
  mentions?: (QuranreflectUser & { locations: string[] | string })[];
  tags?: Tag[];
  recentComment?: PostComment | null;
  references?: Reference[];
}

export default AyahReflection;
