export const REVALIDATION_PERIOD_ON_ERROR_SECONDS = 35;
export const ONE_WEEK_REVALIDATION_PERIOD_SECONDS = 604800; // 7 days
export const ONE_MONTH_REVALIDATION_PERIOD_SECONDS = 2592000; // 30  days
