enum SliceName {
  THEME = 'theme',
  READING_PREFERENCES = 'readingPreferences',
  QURAN_READER_STYLES = 'quranReaderStyles',
  TRANSLATIONS = 'translations',
  TAFSIRS = 'tafsirs',
  AUDIO_PLAYER_STATE = 'audioPlayerState',
  DEFAULT_SETTINGS = 'defaultSettings',
  BANNER = 'banner',
  NAVBAR = 'navbar',
  RADIO = 'radio',
  SESSION = 'session',
  VOICE_SEARCH = 'voiceSearch',
  WELCOME_MESSAGE = 'welcomeMessage',
  COMMAND_BAR = 'commandBar',
  CONTEXT_MENU = 'contextMenu',
  FONT_FACES = 'fontFaces',
  HIGHLIGHTED_LOCATIONS = 'highlightedLocation',
  NOTES = 'notes',
  READING_TRACKER = 'readingTracker',
  READING_VIEW_HOVERED_VERSE = 'readingViewHoveredVerse',
  SIDEBAR_NAVIGATION = 'sidebarNavigation',
  SEARCH = 'search',
  LOCALE = 'locale',
}

export default SliceName;
