enum Event {
  START_STREAM = 'START_STREAM',
  END_STREAM = 'END_STREAM',
  SEARCH_LOADING = 'SEARCH_LOADING',
  SEARCH_RESULT = 'SEARCH_RESULT',
  PARTIAL_TRANSCRIPT = 'PARTIAL_TRANSCRIPT',
  ERROR = 'ERROR',
}

export default Event;
