name: Purge CF Cache

on: [deployment_status]

jobs:
  purge_cache:
    name: Purge CF Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Call CF
        env:
          CF_AUTH_KEY: ${{ secrets.CF_AUTH_KEY }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          echo '${{ toJSON(github) }}'
